name: permission_handler_android
description: Permission plugin for Flutter. This plugin provides the Android API to request and check permissions.
homepage: https://github.com/baseflow/flutter-permission-handler
version: 11.0.0
publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    git:
      url: 'https://github.com/MilosKarakas/flutter-permission-handler.git'
      path: permission_handler_platform_interface
      ref: '#1108'

dev_dependencies:
  flutter_lints: ^1.0.4
  plugin_platform_interface: ^2.0.0
